/** [u0, u1, v0, v1] in relative frame coordinates (0-1), the Design Bible order. */
export type Box = [number, number, number, number];
export type Blend = 'normal' | 'multiply' | 'screen';

export type SceneLayerSet = { rect: Box; src: string[] };

/** Generated by tools/make-temp-assets.ts (later: from QA-passed assets in assets/manifest.json). */
export type Scene = {
  room: string;
  style: string;
  frame: string;
  temporary: boolean;
  source: string;
  aspect: number;
  mobile_center_u: number;
  widths: { lo: number; hi: number };
  formats: ('avif' | 'webp')[];
  base: { id: string; z: number; blend: Blend; src: string; widths: number[]; temporary: boolean }[];
  slots: Record<
    string,
    {
      z: number;
      depth: number;
      temporary: boolean;
      /** the product's own box in the frame (its ring on the stage); null when the product is not in the picture */
      ring?: Box | null;
      product: SceneLayerSet | null;
      shadow: SceneLayerSet | null;
      light: SceneLayerSet | null;
    }
  >;
  depth: { src: string; width: number };
  hall: { src: string; widths: number[]; temporary: boolean };
  transitions: Record<string, { from: string; to: string; frames: number; fps: number; width: number; src: string; temporary: boolean }>;
};

export type LayerSpec = {
  /** stable texture key: src without width/format */
  key: string;
  src: string;
  kind: 'base' | 'product' | 'shadow' | 'light';
  slot: string | null;
  rect: Box;
  blend: Blend;
  z: number;
};

export type Cam = { cu: number; cv: number; z: number };
export type Viewport = { w: number; h: number };
