/**
 * catalog.full.json (built from the repo) → idempotent SQL for D1.
 * Catalog tables are replaced; commerce tables (orders, carts, payments) are never touched.
 * Products that left the catalog stay in D1 (orders reference them) with visible = 0.
 *
 *   tsx api/scripts/seed.ts            → ../.generated/seed.sql
 *   wrangler d1 execute DB --local --file ../.generated/seed.sql
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { FullCatalog } from '@hd/shared';

const here = dirname(fileURLToPath(import.meta.url));
const GENERATED = resolve(here, '../../.generated');

export function sql(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') {
    if (!Number.isFinite(v)) throw new Error(`non-finite number in seed: ${v}`);
    return String(v);
  }
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${String(v).replace(/'/g, "''")}'`;
}

const row = (vals: unknown[]): string => `(${vals.map(sql).join(', ')})`;

export function buildSeedSql(cat: FullCatalog): string {
  const now = cat.built_at;
  const s = cat.economics.settings;
  const out: string[] = [
    `-- generated by api/scripts/seed.ts from catalog ${cat.version} (${cat.mode}, commit ${cat.git_commit})`,
    'PRAGMA defer_foreign_keys = ON;',
    'DELETE FROM slot_options;',
    'DELETE FROM slots;',
    'UPDATE products SET visible = 0;',
    'UPDATE product_variants SET active = 0;',
  ];

  const meta: Record<string, string> = {
    catalog_version: cat.version,
    catalog_mode: cat.mode,
    git_commit: cat.git_commit,
    built_at: cat.built_at,
    shipping_options: JSON.stringify(cat.shipping),
    hidden_products: JSON.stringify(cat.hidden),
    invalid_cards: JSON.stringify(cat.invalid_cards),
  };
  for (const [k, v] of Object.entries(meta))
    out.push(`INSERT INTO catalog_meta (key, value) VALUES ${row([k, v])} ON CONFLICT(key) DO UPDATE SET value = excluded.value;`);

  out.push(
    `INSERT INTO economics_settings (id, fx_usd_ils, vat_rate, payment_fee_rate, payment_fee_fixed_agorot, returns_reserve_rate, cac_agorot, target_margin_rate, default_shipping_usd_cents, packaging_agorot, items_per_order, bundle_factor, freight_method, shipping_fee_economy_agorot, shipping_fee_express_agorot, free_shipping_threshold_agorot, defaults_used, imported_at, source) VALUES ${row(
      [
        'current',
        s.fx_usd_ils,
        s.vat_rate,
        s.payment_fee_rate,
        Math.round(s.payment_fee_fixed_ils * 100),
        s.returns_reserve_rate,
        Math.round(s.cac_ils * 100),
        s.target_margin_rate,
        Math.round(s.default_shipping_usd * 100),
        Math.round(s.packaging_ils * 100),
        s.items_per_order,
        s.bundle_factor,
        s.freight_method,
        Math.round(s.shipping_fee_economy_ils * 100),
        Math.round(s.shipping_fee_express_ils * 100),
        s.free_shipping_threshold_ils === null ? null : Math.round(s.free_shipping_threshold_ils * 100),
        JSON.stringify(cat.economics.defaults_used),
        now,
        cat.economics.sources.settings,
      ],
    )} ON CONFLICT(id) DO UPDATE SET fx_usd_ils = excluded.fx_usd_ils, vat_rate = excluded.vat_rate, payment_fee_rate = excluded.payment_fee_rate, payment_fee_fixed_agorot = excluded.payment_fee_fixed_agorot, returns_reserve_rate = excluded.returns_reserve_rate, cac_agorot = excluded.cac_agorot, target_margin_rate = excluded.target_margin_rate, default_shipping_usd_cents = excluded.default_shipping_usd_cents, packaging_agorot = excluded.packaging_agorot, items_per_order = excluded.items_per_order, bundle_factor = excluded.bundle_factor, freight_method = excluded.freight_method, shipping_fee_economy_agorot = excluded.shipping_fee_economy_agorot, shipping_fee_express_agorot = excluded.shipping_fee_express_agorot, free_shipping_threshold_agorot = excluded.free_shipping_threshold_agorot, defaults_used = excluded.defaults_used, imported_at = excluded.imported_at, source = excluded.source;`,
  );

  for (const r of cat.rooms) {
    out.push(
      `INSERT INTO rooms (id, house_room_id, name_he, style, frame, slots_version, built) VALUES ${row([r.id, r.house_room_id, r.name_he, r.style, r.frame, r.slots_version, r.built])} ON CONFLICT(id) DO UPDATE SET house_room_id = excluded.house_room_id, name_he = excluded.name_he, style = excluded.style, frame = excluded.frame, slots_version = excluded.slots_version, built = excluded.built;`,
    );
  }

  for (const p of cat.products) {
    const data = {
      materials_he: p.materials_he,
      dimensions_cm: p.dimensions_cm,
      color_hex: p.color_hex,
      shipping_days: p.shipping_days,
      notes_he: p.notes_he,
      set_of: p.set_of,
      nordic_score: p.nordic_score,
    };
    out.push(
      `INSERT INTO products (id, room_id, slot_id, name_he, name_provisional, name_supplier, category, description_he, status, source_path, supplier_name, supplier_url, supplier_sku, cost_usd_cents, shipping_usd_cents, shipping_from_default, shipping_source, sell_qty, fx_usd_ils_at_import, retail_agorot, compare_at_agorot, price_provisional, visible, data_json, catalog_version, updated_at) VALUES ${row(
        [
          p.id,
          p.room,
          p.slot,
          p.name_he,
          p.name_provisional,
          p.name_supplier,
          p.category,
          p.description_he,
          p.status,
          p.source_path,
          p.supplier.name,
          p.supplier.url,
          p.supplier.sku,
          p.cost_usd_cents,
          p.shipping_usd_cents,
          p.shipping_from_default,
          p.shipping_source,
          p.sell_qty,
          p.fx_usd_ils,
          p.price_agorot,
          p.compare_at_agorot,
          p.price_provisional,
          true,
          JSON.stringify(data),
          cat.version,
          now,
        ],
      )} ON CONFLICT(id) DO UPDATE SET room_id = excluded.room_id, slot_id = excluded.slot_id, name_he = excluded.name_he, name_provisional = excluded.name_provisional, name_supplier = excluded.name_supplier, category = excluded.category, description_he = excluded.description_he, status = excluded.status, source_path = excluded.source_path, supplier_name = excluded.supplier_name, supplier_url = excluded.supplier_url, supplier_sku = excluded.supplier_sku, cost_usd_cents = excluded.cost_usd_cents, shipping_usd_cents = excluded.shipping_usd_cents, shipping_from_default = excluded.shipping_from_default, shipping_source = excluded.shipping_source, sell_qty = excluded.sell_qty, fx_usd_ils_at_import = excluded.fx_usd_ils_at_import, retail_agorot = excluded.retail_agorot, compare_at_agorot = excluded.compare_at_agorot, price_provisional = excluded.price_provisional, visible = 1, data_json = excluded.data_json, catalog_version = excluded.catalog_version, updated_at = excluded.updated_at;`,
    );
    for (const v of p.variants) {
      out.push(
        `INSERT INTO product_variants (id, product_id, label_he, supplier_sku, fulfillment_source, active) VALUES ${row([v.id, p.id, v.label_he, p.supplier.sku, p.fulfillment_source, true])} ON CONFLICT(id) DO UPDATE SET label_he = excluded.label_he, supplier_sku = excluded.supplier_sku, fulfillment_source = excluded.fulfillment_source, active = 1;`,
      );
    }
  }

  for (const r of cat.rooms) {
    for (const sl of r.slots) {
      out.push(
        `INSERT INTO slots (room_id, id, name_he, category, placement, z, set_of, has_light, has_shadow, hotspot, zoom_frame) VALUES ${row([
          r.id,
          sl.id,
          sl.name_he,
          sl.category,
          sl.placement,
          sl.z,
          sl.set_of,
          sl.has_light,
          sl.has_shadow,
          sl.hotspot ? JSON.stringify(sl.hotspot) : null,
          sl.zoom_frame ? JSON.stringify(sl.zoom_frame) : null,
        ])};`,
      );
      for (const o of sl.options) {
        out.push(
          `INSERT INTO slot_options (room_id, slot_id, style, position, product_id, placeholder, is_default) VALUES ${row([r.id, sl.id, r.style, o.position, o.product_id, o.placeholder, o.is_default])};`,
        );
      }
    }
  }
  return out.join('\n') + '\n';
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const cat = JSON.parse(readFileSync(resolve(GENERATED, 'catalog.full.json'), 'utf8')) as FullCatalog;
  const text = buildSeedSql(cat);
  writeFileSync(resolve(GENERATED, 'seed.sql'), text);
  console.log(`seed.sql: ${cat.products.length} products, ${cat.rooms.length} rooms (catalog ${cat.version})`);
}
